language: go

go:
  - 1.13.x
  - 1.14.x

env:
  global:
    - GO111MODULE=on

before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v1.24.0
  - go get github.com/securego/gosec/cmd/gosec

script:
  - make
